### ISSUE TITLE
RabbitMQ

### ISSUE THREAD

**Issue by safecorners** [safecornerscoffee/kickstarter-clone#4]
- [x] [Spring guide Messaging with RabbitMQ](https://spring.io/guides/gs/messaging-rabbitmq/)
- [ ] [Spring AMQP Reference](https://docs.spring.io/spring-amqp/reference/html/)
- [ ] [Spring AMQP Reference 4.1.13. Delayed Message Exchange](https://docs.spring.io/spring-amqp/reference/html/#delayed-message-exchange)
- [ ] [Spring AMQP Reference 4.3 Sample Applications](https://docs.spring.io/spring-amqp/reference/html/#sample-apps)
- [x] [RabbitMQ docker image](https://hub.docker.com/_/rabbitmq)
- [ ]  [RabbitMQ Tutorials with Spring AMQP ](https://www.rabbitmq.com/getstarted.html)
- [ ] [Scheduling Messages with RabbitMQ](https://blog.rabbitmq.com/posts/2015/04/scheduling-messages-with-rabbitmq)
- [ ] [RabbitMQ Delayed Message Plugin](https://github.com/rabbitmq/rabbitmq-delayed-message-exchange)

**Comment by safecorners** [comment]
docker-compose.yaml
```yaml
version: "3"
services:
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: kickstarter
      RABBITMQ_DEFAULT_PASS: kickstarter
```

**Comment by safecorners** [comment]
application.yaml
```yaml
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: kickstarter
    password: kickstarter

```
